package br.niedunicamp.pojo;

public enum NotificationType {
    // Wall
    NEW_WALL_POST, NEW_WALL_POST_BY_TEACHER, NEW_POST_COMMENTS, NEW_POST_LIKES, NEW_POST_COMMENT_BY_TEACHER,

    // Activity
    ACTIVITY_PUBLISHED, ACTIVITY_SCHEDULED, ACTIVITY_DELETED, ACTIVITY_UPDATED,

    ACTIVITY_SUBMISSION_STARTED, ACTIVITY_SUBMISSION_ENDED,

    ACTIVITY_GRADE_RELEASED,

    // Participation
    NEW_STUDENT,

    // Grades
    FINAL_GRADE_RELEASED, GRADE_CONFIG_UPDATED,

    // Material
    NEW_MATERIAL,
}